<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.*">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="EduSapienxa.Application\EduSapienxa.Application.csproj" />
    <ProjectReference Include="EduSapienxa.Infrastructure\EduSapienxa.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="EduSapienxa.Domain\**" />
    <Compile Remove="EduSapienxa.Infrastructure\**" />
    <Compile Remove="EduSapienxa.Application\**" />
    <EmbeddedResource Remove="EduSapienxa.Domain\**" />
    <EmbeddedResource Remove="EduSapienxa.Infrastructure\**" />
    <EmbeddedResource Remove="EduSapienxa.Application\**" />
    <None Remove="EduSapienxa.Domain\**" />
    <None Remove="EduSapienxa.Infrastructure\**" />
    <None Remove="EduSapienxa.Application\**" />
  </ItemGroup>

</Project>
